// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNDArKVMHysGfh0NIFd72EJBym5MLfHlA',
    appId: '1:298032349152:web:3822e769889f8db856b585',
    messagingSenderId: '298032349152',
    projectId: 'note-diary-exam',
    authDomain: 'note-diary-exam.firebaseapp.com',
    storageBucket: 'note-diary-exam.appspot.com',
    measurementId: 'G-LQ48289GSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEWU7s_tlpBs3Mu3xu4V23SmtW1JtLTSY',
    appId: '1:298032349152:android:f4909f7d8187446356b585',
    messagingSenderId: '298032349152',
    projectId: 'note-diary-exam',
    storageBucket: 'note-diary-exam.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy1Bst9ZrkPpQzyBnaZfK4WZVzsYQ0SJc',
    appId: '1:298032349152:ios:7168ad7f6b9dfc7556b585',
    messagingSenderId: '298032349152',
    projectId: 'note-diary-exam',
    storageBucket: 'note-diary-exam.appspot.com',
    iosBundleId: 'com.example.contactdairyExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy1Bst9ZrkPpQzyBnaZfK4WZVzsYQ0SJc',
    appId: '1:298032349152:ios:7168ad7f6b9dfc7556b585',
    messagingSenderId: '298032349152',
    projectId: 'note-diary-exam',
    storageBucket: 'note-diary-exam.appspot.com',
    iosBundleId: 'com.example.contactdairyExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNDArKVMHysGfh0NIFd72EJBym5MLfHlA',
    appId: '1:298032349152:web:3513ace2221e59f456b585',
    messagingSenderId: '298032349152',
    projectId: 'note-diary-exam',
    authDomain: 'note-diary-exam.firebaseapp.com',
    storageBucket: 'note-diary-exam.appspot.com',
    measurementId: 'G-08P5WKBBRJ',
  );
}
